"""Initial migration

Revision ID: 600162349452
Revises: 
Create Date: 2026-03-10 14:00:58.145664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600162349452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)
        batch_op.create_index(batch_op.f('ix_categorias_slug'), ['slug'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('direccion_entrega', sa.Text(), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_numero_pedido'), ['numero_pedido'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=True)

    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_pedido')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_sku'))
        batch_op.drop_index(batch_op.f('ix_productos_nombre'))

    op.drop_table('productos')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_numero_pedido'))

    op.drop_table('pedidos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_slug'))
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    # ### end Alembic commands ###
